version: '3.8'

services:
  news_delivery_service:
    container_name: news-delivery-container
    image: news_delivery-services:0.0.1
    restart: on-failure
    build:
      context: .
    ports:
      - 8082:8082
    networks:
      - mongo-compass_mongo-network

networks:
  mongo-compass_mongo-network:
    external: true
