version: '3.8'

networks:
  my_network:

services:
  news_fetch_service:
    container_name: news-fetch-container
    image: news_fetch-services:0.0.1
    restart: on-failure
    build:
      context: .
    ports:
      - 8080:8080
    # environment:
    #   - RABBITMQ_URL=amqp://localhost
    # depends_on:
    #   - rabbitmq
    # links:
    #   - rabbitmq
    networks:
      - my_network

